### ISSUE TITLE
SR305 intel realsense behavior 

### ISSUE THREAD

**Issue by devshank3** [JetsonHacksNano/installLibrealsense#30]
Currently i tested SR305 in my laptop with realsense viewer and it was giving good dynamic results 

But now in the realsense viewer in jetson nano its not giving any good depth para until we go so close to the camera (20cm) 

Any version issue with jetson nano or kernal issue ?

**Comment by JetsonHacksNano** [comment]
None that I know. It has been a while since this issue, so it is being closed.

This is an issue with librealsense, not the installer scripts. You will probably get a better response from the librealsense repository https://github.com/IntelRealSense/librealsense. If you encounter further  problems, please open a new issue.

**Comment by devshank3** [comment]
![image](https://user-images.githubusercontent.com/52159502/156760263-98909040-cad5-442f-aca4-ce8d8ab0a5ca.png)

This issue is fixed with https://github.com/IntelRealSense/librealsense/releases/tag/v2.47.0

**Comment by JetsonHacksNano** [comment]
Wow, it  took two years!
